## **2: Preprocessing in sklearn**

### **2.1 Scaling**

##### **2.1.1 StandardScaler**
StandardScaler is used to standardize (normalize) data so that:
* Mean = 0
* Standard Deviation = 1

**Formula**
$$x_{scaled} = \frac{X - \mu}{\sigma}$$

* μ = mean
* σ = standard deviation	​

**Without scaling:**
* Features with large values dominate
* Model becomes biased

**Syntax:**
```bash
scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
```
**Parameters:**
* copy → copy the original data or not
* with_mean → center data to maen = 0
* with_std → scale data to std = 1

In [7]:
from sklearn.preprocessing import StandardScaler
import  numpy as np

scaler = StandardScaler()
X = np.array([
    [20, 20000],
    [30, 50000],
    [40, 100000]
])

print(X)

# standardized_data = scaler.fit_transform(X) or

scaler.fit(X)
standardized_data = scaler.transform(X)
print(standardized_data)


[[    20  20000]
 [    30  50000]
 [    40 100000]]
[[-1.22474487 -1.1111678 ]
 [ 0.         -0.20203051]
 [ 1.22474487  1.31319831]]


**Important Points**
* Always fit on training data only ✅
* Then transform both train & test
* Do NOT fit on test data ❌
* .transform() returns standardized (scaled) data

#### **2.1.2 MinMaxScaler**

MinMaxScaler is used to scale data into a fixed range, usually: $[0,1]$

**Formula**
$$x_{scaled} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

**Converts:**
* smallest value → 0
* largest value → 1
* reat values → between 0 and 1

**Syntax:**
```bash
scaler = MinMaxScaler(feature_range=(min, max), copy=True)
```

**Parameters:**
* feature_range → (min, max)
* copy



In [ ]:
from sklearn.preprocessing import MinMaxScaler

minmaxscaler = MinMaxScaler()
X = [[10], [20], [30]]

print(X)
minmaxscaler.fit(X) # 👉 sklearn expects data in 2D format:
standardized_data = minmaxscaler.transform(X)
print(standardized_data)

[[10], [20], [30]]
[[0. ]
 [0.5]
 [1. ]]


### **2.2 Encoding**

#### **2.2.1 LabelEncoding**

LabelEncoder is used to convert categorical (text) data into numbers

**Syntax:**
```bash
encoder = LabelEncoder()
```

In [15]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
X = ["cat", "dog", "cat", "cow"]

print(X)
encoder.fit(X)
encoded_data = encoder.transform(X)
print(encoded_data)

inversed_data = encoder.inverse_transform(encoded_data)
print(inversed_data)


['cat', 'dog', 'cat', 'cow']
[0 2 0 1]
['cat' 'dog' 'cat' 'cow']


#### **2.2.2 OneHotEncoder**

OneHotEncoder converts categorical data into binary (0/1) columns
* Instead of giving numbers like 0,1,2, It creates separate columns for each category ✅

**Example:**
Color = ["Red", "Green", "Blue"]
| Red | Green | Blue |
| --- | ----- | ---- |
| 1   | 0     | 0    |
| 0   | 1     | 0    |
| 0   | 0     | 1    |

**Syntax:**
```bash
encoder = OneHotEncoder(
    categories='auto',
    drop=None,
    sparse_output=True,
    dtype=float
)
```


**Parameters:**
* categories
* drop → drop first column
* sparse_output → sparse matrix or not
* dtype



In [42]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
X = np.array([["Red"], ["Green"], ["Blue"]])

encoder = OneHotEncoder(sparse_output=False) # if True then print(X_encoded.toarray())

encoder.fit(X)

X_encoded = encoder.transform(X)

print(X_encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


### **2.3 Handling Missing Values**

SimpleImputer is used to fill missing values (NaN) in your dataset.

**Syntax:**
```bash
imputer = SimpleImputer(
    missing_values=np.nan,
    strategy='mean',
    fill_value=None
)
```

**Parameters:**
* missing_values -> What value should be treated as missing like: np.nan, None, 0, "?"
* strategy → 'mean', 'median', 'most_frequent', 'constant'
* fill_value -> Used only when strategy = 'constant'

**strategy** : How to fill missing values

* 'mean' → average (for numeric data)
* 'median' → middle value (good for outliers)
* 'most_frequent' → most common value (good for categorical)
* 'constant' → fixed value



In [45]:
import numpy as np
from sklearn.impute import SimpleImputer

X = np.array([[1], [2], [np.nan], [4]])
imputer = SimpleImputer(strategy='mean')

X_new = imputer.fit_transform(X)
print(X)
print(X_new)



[[ 1.]
 [ 2.]
 [nan]
 [ 4.]]
[[1.        ]
 [2.        ]
 [2.33333333]
 [4.        ]]


##### **2.4 Feature Selection**

Feature Selection = choosing only **important features** (columns) from your dataset and **removing useless** ones.

**Why we use it ?**
* Improves model accuracy
* Reduces overfitting
* Makes model faster
* Removes noise/unnecessary data







##### **2.4.1 Filter Methods**

Filter methods wo techniques hoti hain jo features ko select karti hain based on statistical tests, bina model train kiye.

**Types of Filter Methods**

**1. SelectKBest** : Top K best features select karta hai

**Important score functions:**
* chi2 → categorical data
* f_classif → classification
* f_regression → regression


In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

selector = SelectKBest(score_func=chi2, k=2)

x_new = selector.fit_transform(X, Y)

**2. SelectPercentile** : Top percentage features select karta hai

In [ ]:
from sklearn.feature_selection import SelectPercentile,  f_classif

selector = SelectPercentile(score_func=f_classif, percentile=20)
X_new = selector.fit_transform(X, y)

**3. Variance Threshold** : Low variance wale features remove karta hai
* Agar feature almost constant hai → useless

In [46]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.2)
X_new = selector.fit_transform(X)

**4. Correlation-based Selection** : Highly correlated features remove
* Agar 2 features same info de rahe hain → ek hata do
* We don't have this function in sklearn so we manuallt implement it

#### **Advantages**
* ✅ Fast (no model training)
* ✅ Simple
* ✅ Overfitting kam hota hai

##### **2.4.2 Wrapper Methods**

Wrapper methods select features by actually training a model and checking which combination of features gives the best performance.

**Types of Wrapper Methods**

**1. RFE (Recursive Feature Elimination)**: Step-by-step least important features remove karta hai


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

model = LogisticRegression()
selector = RFE(model, n_features_to_select=3)

X_new = selector.set_fit_request(X, y)


**Working:**
* Model train hota hai
* Feature importance milti hai
* Least important feature remove
* Repeat until desired features

**2. RFECV (RFE with Cross Validation)** : Automatically finds best number of features.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFECV

model - LogisticRegression()

selector = RFECV(model, cv=5)

X_new = selector.fit_transform(X, y)

**3. Sequential Feature Selection** : Step-by-step features add/remove karta hai

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

model - LogisticRegression()
sfs = SequentialFeatureSelector(model, n_features_to_select=3, direction='forward')
X_new = sfs.fit_transform(X, y)

#### **Advantages**
* ✅ Better accuracy than filter methods
* ✅ Feature interaction consider karta hai
* ✅ More powerful

##### **2.4.3 Embedded Methods**

Embedded methods perform feature selection during the model training process itself.

**Feature selection + model training happen together**

**Simple Intuition**
* Filter methods → no model used
* Wrapper methods → model used multiple times
* Embedded methods → model used once, and feature selection happens inside it

**So it’s a middle ground:**
* Faster than wrapper
* Smarter than filter

**Common Embedded Methods**

**1. Lasso Regression (L1 Regularization)** : Shrinks some feature coefficients to zero


In [ ]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=0.1)
model.fit(X, y)

**2. Ridge Regression (L2 Regularization)** : Reduces coefficients but does NOT make them zero
* Used more for regularization, not strict feature selection

In [ ]:
from sklearn.linear_model import Lasso

model = Lasso(alpha=1.0)
model.fit(X, y)

**3. Tree-Based Models (Feature Importance)** : Models like decision trees automatically rank features

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X, y)
importance = model.feature_importances_

**4. SelectFromModel** : Automatically selects important features from a trained model

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import Lasso

selector = SelectFromModel(Lasso(alpha=0.1))
X_new = selector.fit_transform(X, y)

#### **Advantages**

* ✅ Faster than wrapper methods
* ✅ Considers feature interactions
* ✅ More accurate than filter methods