## **6: Dimensionality Reduction in sklearn**

Dimensionality Reduction means **reducing the number of features** (columns) in a dataset while keeping the important information.

### **6.1 PCA (Principal Component Analysis)**

PCA reduces number of features while keeping most important information

**Syntax:**
```bash
model = PCA(
    n_components=None,
    copy=True,
    whiten=False,
    svd_solver='auto'
)
```

**Parameters (simple language)**
* n_components
    * number of components (features to keep)
    * can be:
        * int (e.g., 2)
        * float (e.g., 0.95 → keep 95% variance)
* whiten → True/False
    * makes output data normalized (mean=0, variance=1)
* svd_solver → 'auto', 'full', 'randomized'
    * method used to compute PCA
* random_state
    * for reproducible results

**PCA uses:**
* .fit() → learn components
* .transform() → reduce data
* .fit_transform() → both

**Important Attributes:**
```bash
model.components_
model.explained_variance_
model.explained_variance_ratio_
```

* components_ → principal directions
* explained_variance_ → variance per component
* explained_variance_ratio_ → importance %


In [1]:
from sklearn.decomposition import PCA
import numpy as np

# Sample dataset (3 features)
X = np.array([
    [2, 3, 4],
    [3, 4, 5],
    [5, 6, 7],
    [8, 9, 10]
])

# Create model (reduce to 2 features)
model = PCA(n_components=2)

# Fit & Transform
X_reduced = model.fit_transform(X)

print("Reduced Data:\n", X_reduced)

# 1️⃣ Components (directions)
print("Components:\n", model.components_)

# 2️⃣ Explained Variance (importance value)
print("\nExplained Variance:\n", model.explained_variance_)

# 3️⃣ Explained Variance Ratio (importance %)
print("\nExplained Variance Ratio:\n", model.explained_variance_ratio_)

Reduced Data:
 [[-4.33012702e+00 -3.41227522e-16]
 [-2.59807621e+00  1.09030985e-16]
 [ 8.66025404e-01 -2.12354400e-17]
 [ 6.06217783e+00 -1.93972745e-16]]
Components:
 [[ 0.57735027  0.57735027  0.57735027]
 [ 0.81649658 -0.40824829 -0.40824829]]

Explained Variance:
 [2.10000000e+01 5.54667824e-32]

Explained Variance Ratio:
 [1.00000000e+00 2.64127535e-33]


### **6.3 LDA (Linear Discriminant Analysis)**

* LDA separates classes and can reduce dimensions at the same time ⭐

**Syntax**
```bash
model = LinearDiscriminantAnalysis(
    solver='svd',
    shrinkage=None,
    n_components=None
)
```

**Parameters (simple language)**
* solver → 'svd', 'lsqr', 'eigen' ⭐
    * method used to solve LDA
    * 'svd' = default and most used
* shrinkage
    * used to reduce overfitting
    * works only with 'lsqr' or 'eigen'
* n_components ⭐
    * number of new features (dimensions) to keep
    * used for dimensionality reduction


**Methods:**
```bash
model.fit(X, y)
model.transform(X)
model.fit_transform(X, y)
model.predict(X)
```

**Important Attributes:**
```bash
model.coef_
model.classes_
```
* model.coef_ → tells how much each feature influences the prediction (feature importance/weights)
* model.classes_ → shows all the possible output classes the model can predict

In [2]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Small dataset
X = np.array([
    [1, 2], [2, 3], [3, 4],
    [8, 8], [9, 8], [8, 9]
])

y = np.array([0, 0, 0, 1, 1, 1])  # class labels

# Create model
model = LinearDiscriminantAnalysis()

# Train
model.fit(X, y)

# Predict
y_pred = model.predict(X)
print("Predictions:", y_pred)

Predictions: [0 0 0 1 1 1]
